### PR TITLE
windows support in full

### LINKED ISSUE #94: Getting gobrew's latest version should have a timeout && should not fail on rate limit exceeded. Just skip with a warning.
https://github.com/kevincobain2000/gobrew/blob/3d7561d475d3f77cef1242d5a7de7a2b418537e4/gobrew.go#L463-L466

### PR DESCRIPTION
**Pull request by kevincobain2000**
Fixes #94

### CODE REVIEW

File: gobrew.go [hunk 1]
```diff
@@ -463,10 +463,6 @@ func (gb *GoBrew) Use(version string) {
 // Version of GoBrew
 func (gb *GoBrew) Version(currentVersion string) {
 	utils.Infoln("[INFO] gobrew version is " + currentVersion)
-	if "v"+currentVersion != gb.getLatestVersion() {
```
Comment (kevincobain2000) [inline gobrew.go:466]: Skipping this because it makes an API call and response can be slow.
We already use getLatestVersion at the time of `upgrade` therefore removing it from here.

Comment (juev) [reply gobrew.go:466]: 👍

File: README.md [hunk 2]
```diff
@@ -314,3 +314,4 @@ curl https://raw.githubusercontent.com/kevincobain2000/gobrew/master/completions
 - v1.7.7 - Windows support?
 - v1.7.8 - Windows support, self-update fixes
 - v1.7.9 - Windows fix ups and bash-completions
+- v1.8.9 - Windows support, including actions
```
Comment (juev) [inline README.md:317]: Why 1.8.9? If we change major version we should restart minor? Or I don’t understand something?

Comment (kevincobain2000) [reply README.md:317]: whoops

Comment (kevincobain2000) [reply README.md]: I meant `1.8.0`. I copied the previous line :(

**Review by juev — APPROVED** [review]
🏎️
